---
name: Lint Role

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip3 install ansible-lint

      - name: Run ansible-lint
        run: ansible-lint .

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip3 install yamllint

      - name: Run ansible-lint
        run: yamllint .
